### ISSUE TITLE
autoitem div has no body

### ISSUE THREAD

**Issue by kochd** [aliask/fuzzycomplete#4]
I had to change https://github.com/aliask/fuzzycomplete/blob/master/src/js/fuzzycomplete.js#L142

```diff
- resultsRow.text(result[options.display]);
+ resultsRow.text(result.item[options.display]);
```
to get it to fill my div (__autoitem)

**Comment by aliask** [comment]
Hi Daniel.

I'm having difficulty reproducing your issue. When I check `result` at this point, I see `{ code: "456", itemName: "batz" }`, for example. No `item` in the object. The `__autoitem` element works fine.

Which browser are you using?

By the way, it's quite difficult for me to see your original comment with all the details if you edit it out! Just post a second comment :)

Cheers,
Will
