### ISSUE TITLE
Not compatible with version 6.x of fuse.js

### ISSUE THREAD

**Issue by pfortin-expertime** [aliask/fuzzycomplete#6]
After :

`results.forEach(function(result, i) {`

should add :

`result = result.item;`

to make it work with Fuse.js 6+

**Comment by aliask** [comment]
Hi, thanks for the report. 

I've just pushed a change in 4d9b3dd which should allow compatibility with both old and new versions of Fuse, let me know if you have any issues!

Cheers,
Will

**Comment by legweilo** [comment]
Hey, thank you for the quick update !
I was too lazy for a PR sorry ;)
